#! /usr/bin/env zsh
# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# Enable aliases to be sudo’ed
alias sudo="sudo "

# use nvim in place of vim/vi
alias vim="nvim"
alias vi="nvim"
# fuzzy search for file and open in vim
alias vf="vim \$(fzf)"

# Recursively delete `.DS_Store` files
alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"

# Disc utils
alias diskspace_report="df -P -kHl"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs & the useless sleepimage to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo grm -rf $HOME/.Trash; sudo rm -rtv /private/var/log/asl/*.asl; sudo rm /private/var/vm/sleepimage"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Show/hide all desktop icons (useful when presenting)
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# zshrc config
alias zshrc="${EDITOR} ~/.zshrc"
alias reload="source ~/.zshrc && echo 'Shell config reloaded from ~/.zshrc'"

# zsh.local config
alias localrc="if [[ -a ~/.zsh.local ]]; then ${EDITOR} ~/.zsh.local; fi"

#alias git="~/.push-confirm && git"
alias git=git

# character based diff of two files
alias diffchar="git diff --word-diff=color --word-diff-regex=. --no-index"

# use ripgrep instead of silversearcher
alias ag=rg

# use phpstan from docker
alias phpstan='docker run -v $PWD:/app --rm phpstan/phpstan'
alias php-cs-fixer='docker run -v $PWD:/project --rm herloct/php-cs-fixer'

# xclip clipboard
alias xcc='xclip -selection clipboard'
