#! /usr/bin/env zsh

# Defaults
export SHELL=zsh
export EDITOR='nvim'
export DEFAULT_USER=andrewwright
export WLR_DRM_NO_MODIFIERS=1

# Directory Env Vars
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/personal

# 1password CLI
export OKTA_API_TOKEN="op://Employee/hd7ect55767myodzoilo2k7eau/token"
export DD_API_KEY="op://Employee/Datadog API Keys - CLI/api key"
export DD_APP_KEY="op://Employee/Datadog API Keys - CLI/app key"
export LUMOS_ACCESS_TOKEN="op://Employee/me2b6wg37qkgkeghtaz7762h3i/credential"
export CLOUDFLARE_API_TOKEN="op://Employee/Cloudflare API Token/token"

# set virtualenvwrapper to global python3
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# SSH
# export SSH_KEY_PATH="~/.ssh/id_rsa"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# use ripgrep for fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
