if [ -f $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
  source $HOME/.nix-profile/etc/profile.d/nix.sh
fi

# Fixes a bug where programs opening file picker would crash
export XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/local/share:/usr/share

# support for nix dir-env
eval "$(direnv hook zsh)"

# Directories to be prepended to $PATH
declare -a dirs_to_prepend
dirs_to_prepend=(
  "/usr/local/bin"
  "/usr/bin"
  "/bin"
  "/usr/sbin/
  /sbin"
  "/usr/local/sbin"
  "/usr/local/git/bin"
  "/usr/local/go/bin"
  "/usr/local/mysql/bin"
  "/usr/local/"
  "$HOME/.local/bin"
  "$HOME/dotfiles/bin"
  "$HOME/go/bin"
  "$HOME/bin"
  "$HOME/.cargo/bin" # rust binaries
  "$HOME/.yarn/bin"
  "$HOME/work/arcanist/arcanist/bin"
  "$HOME/tools/arcanist/bin"
  "$HOME/tools/"
  "$HOME/.krew/bin"
  "/usr/local/opt/bison/bin"
  "/opt/homebrew/bin"
)

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend
export PATH

# --- TODO nixify everything below here ---
# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local
# ssh agent
# Configure gpg agent for ssh
# https://github.com/drduh/YubiKey-Guide#ssh
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# This loads nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
