#!/bin/bash
#
# based off a script by Jon Gjengset
# https://github.com/jonhoo/configs/blob/master/bins/bin/adjust-brightness
cur_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

step="0.03"
step=$(printf "%.0f" "$(echo "$step * $max_brightness" | bc -l)")
curr_per=$(printf "%.0f" "$(echo "$cur_brightness / $max_brightness * 100" | bc -l)")

case "$1" in
	+)
		new_brightness=$(echo "$cur_brightness + $step" | bc -l);
		;;
	-)
		new_brightness=$(echo "$cur_brightness - $step" | bc -l);
		;;
	=)
        echo "$cur_brightness ($curr_per %)";
		exit 1
		;;
	*)
		echo "Usage: $0 +|-"
		exit 1
		;;
esac

if (($new_brightness < 0)); then
	new_brightness="0"
fi
if (($new_brightness > $max_brightness)); then
	new_brightness="$max_brightness"
fi

new_per=$(printf "%.0f" "$(echo "$new_brightness / $max_brightness * 100" | bc -l)")
echo "$cur_brightness -> $new_brightness ($new_per %)"
echo "$new_brightness" | sudo tee /sys/class/backlight/intel_backlight/brightness
